package Strings;
// Find the difference: You are given two Strings s and t, String t is generated by random shuffling String s and
// then add one more letter at random position. Return the letter that was added to it

// Input: s = "abcd", t = "abcde"
// Output: e
// Explanation: 'e' was the letter that was added

public class Problem_13 {
    public static char findTheDiff(String s, String t){
        int total = 0;

        for(int i=0; i<t.length(); i++){
            total = total+t.charAt(i);
        }
        for(int i=0; i<s.length(); i++){
            total = total-s.charAt(i);
        }
        return (char)total;
    }

    public static void main(String[] args) {
        System.out.println(findTheDiff("","y"));
    }
}

